import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { NavigationMenuHeader } from "@/components/Menu";
import Image from "next/image";
import { Viewport } from "next";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  referrer: "origin-when-cross-origin",
  openGraph: {
    title: "heykapil.in",
    description: "Kapil Chaudhary",
    url: "https://heykapil.in",
    siteName: "heykapil.in",
    images: [
      {
        url: "https://heykapil.in/og?title=Kapil Chaudhary",
        width: 1920,
        height: 1080,
        alt: "",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "cyan" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-white text-black font-sans antialiased mx-auto w-full max-w-full",
          fontSans.variable
        )}
      >
        <svg
          className="pointer-events-none fixed top-0 left-0 isolate z-50 opacity-25 mix-blend-normal"
          width="100%"
          height="100%"
        >
          <filter id="pedroduarteisalegend">
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.70"
              numOctaves="5"
              stitchTiles="stitch"
            />
            <feColorMatrix type="saturate" values="0" />
          </filter>
          <rect
            width="100%"
            height="100%"
            filter="url(#pedroduarteisalegend)"
          ></rect>
        </svg>
        <header className="sticky  text-black  top-0 z-9999 py-1 backdrop-filter backdrop-blur-sm  bg-[#f6f6f6]">
          <div className="relative mt-0 z-9999 mx-auto rounded-lg w-full flex-row justify-between  hidden md:flex">
            <div className="flex justify-between w-full max-w-4xl mx-auto">
              <div className="flex">
                <Image
                  src="https://www.gujaratuniversity.ac.in/images/logo.png"
                  alt="logo"
                  width="50"
                  height="50"
                />
              </div>
              <div className="flex">
                <NavigationMenuHeader />
              </div>
            </div>
          </div>
        </header>
        <article className="w-full max-w-full mx-auto">{children}</article>
      </body>
    </html>
  );
}
